site_name: Audio-Workbench Docs
site_url: https://limitlessgreen.github.io/Audio-Workbench/docs
copyright: Copyright &copy; 2026 LimitlessGreen

site_author: LimitlessGreen

# Repository
repo_name: LimitlessGreen/Audio-Workbench
repo_url: https://github.com/LimitlessGreen/Audio-Workbench
edit_uri: blob/main/docs/


theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - search.highlight
    - search.share
    - search.suggest
    - content.tabs.link
    - navigation.indexes

docs_dir: docs

markdown_extensions:
  - admonition
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Python integration (DE): python-integration.md
  - Labeling:
      - Labeling App: labeling/index.md
      - Shortcuts: labeling/shortcuts.md
      - Species format: labeling/species-format.md
      - Xeno-canto format: labeling/xeno-canto-format.md
      - Python integration: labeling/python-integration.md
  - Future Plans: future-plans.md

#plugins:
#  - git-committers

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn