#!/usr/bin/env node
import { execSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');
const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'audio-workbench-types-'));
const generatedDir = path.join(rootDir, 'types', 'generated');
const indexFile = path.join(rootDir, 'types', 'index.d.ts');

function collectDtsFiles(dir, out = []) {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) {
            collectDtsFiles(full, out);
        } else if (entry.isFile() && entry.name.endsWith('.d.ts')) {
            out.push(full);
        }
    }
    return out;
}

try {
    const tscBin = path.join(rootDir, 'node_modules', '.bin', 'tsc');
    // Use a dedicated tsconfig for declaration generation so we can include
    // our shims (types/) and relax strictness without changing the project's
    // main tsconfig.json (which sets noEmit=true for editor checks).
    execSync(
        [
            JSON.stringify(tscBin),
            '-p',
            'tsconfig.types.json',
            `--outDir "${tmpDir}"`,
        ].join(' '),
        { cwd: rootDir, stdio: 'inherit' },
    );

    fs.rmSync(generatedDir, { recursive: true, force: true });
    fs.mkdirSync(generatedDir, { recursive: true });

    const dtsFiles = collectDtsFiles(tmpDir);
    for (const file of dtsFiles) {
        const rel = path.relative(tmpDir, file);
        const target = path.join(generatedDir, rel);
        fs.mkdirSync(path.dirname(target), { recursive: true });
        fs.copyFileSync(file, target);
    }

    fs.writeFileSync(
        indexFile,
        [
            '// Auto-generated by scripts/generate-types.js',
            '// Do not edit manually; regenerate with: npm run types:generate',
            '',
            '// ── Public API ──────────────────────────────────────────────────',
            "export * from './generated/app/BirdNETPlayer';",
            "export { EventBus } from './generated/shared/EventBus';",
            "export type { EventHandler } from './generated/shared/EventBus';",
            '',
            '// ── Headless / testing utilities ────────────────────────────────',
            "export { AudioEngineBase } from './generated/infrastructure/audio/AudioEngineBase';",
            "export { MockAudioEngine } from './generated/infrastructure/audio/MockAudioEngine';",
            "export type { IStorage } from './generated/infrastructure/storage/IStorage';",
            "export { StorageBase } from './generated/infrastructure/storage/IStorage';",
            "export { InMemoryStorageAdapter } from './generated/infrastructure/storage/InMemoryStorageAdapter';",
            "export { LocalStorageAdapter } from './generated/infrastructure/storage/LocalStorageAdapter';",
            '',
            '// ── Domain types ─────────────────────────────────────────────────',
            "export type { UndoCommand } from './generated/domain/undoStack';",
            "export { UndoStack } from './generated/domain/undoStack';",
            "export type { TransportStateName } from './generated/domain/transportState';",
            "export { FrequencyViewport } from './generated/app/FrequencyViewport';",
            '',
            '// ── Event detail types ───────────────────────────────────────────',
            "export type {",
            "    TransportState,",
            "    TransportStateChangeDetail,",
            "    AudioEngineReadyDetail,",
            "    AudioEngineUiUpdateDetail,",
            "    SpectrogramReadyDetail,",
            "    AnnotationEntry,",
            "    SpectrogramLabelEntry,",
            "    LabelFocusDetail,",
            "    UndoChangeDetail,",
            "    AnnotationEventDetail,",
            "    SpectrogramLabelEventDetail,",
            "} from './generated/shared/events';",
            '',
        ].join('\n'),
    );

    console.log('✅ types/index.d.ts generiert');
    console.log('✅ types/generated/*.d.ts aktualisiert');
} finally {
    fs.rmSync(tmpDir, { recursive: true, force: true });
}
