#!/usr/bin/env node
import { execSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');
const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'audio-workbench-types-'));
const generatedDir = path.join(rootDir, 'types', 'generated');
const indexFile = path.join(rootDir, 'types', 'index.d.ts');

function collectDtsFiles(dir, out = []) {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) {
            collectDtsFiles(full, out);
        } else if (entry.isFile() && entry.name.endsWith('.d.ts')) {
            out.push(full);
        }
    }
    return out;
}

try {
    execSync(
        [
            'npx --yes -p typescript tsc',
            'src/BirdNETPlayer.js',
            '--declaration',
            '--allowJs',
            '--emitDeclarationOnly',
            `--outDir "${tmpDir}"`,
            '--module esnext',
            '--target es2020',
            '--lib dom,es2020',
            '--skipLibCheck',
            '--ignoreConfig',
        ].join(' '),
        { cwd: rootDir, stdio: 'inherit' },
    );

    fs.rmSync(generatedDir, { recursive: true, force: true });
    fs.mkdirSync(generatedDir, { recursive: true });

    const dtsFiles = collectDtsFiles(tmpDir);
    for (const file of dtsFiles) {
        const rel = path.relative(tmpDir, file);
        const target = path.join(generatedDir, rel);
        fs.mkdirSync(path.dirname(target), { recursive: true });
        fs.copyFileSync(file, target);
    }

    fs.writeFileSync(
        indexFile,
        [
            '// Auto-generated by scripts/generate-types.js',
            '// Do not edit manually; regenerate with: npm run types:generate',
            "export * from './generated/BirdNETPlayer';",
            '',
        ].join('\n'),
    );

    console.log('✅ types/index.d.ts generiert');
    console.log('✅ types/generated/*.d.ts aktualisiert');
} finally {
    fs.rmSync(tmpDir, { recursive: true, force: true });
}
